apiVersion: kyma.kyma-project.io/v1alpha1
kind: LongOperation
metadata:
  name: longoperation-sample
spec:
  constantProcessingTime: 20
  randomProcessingTime: 10
  bigPayload: "veryLongPayloadHere maybe 10 KiB"
