apiVersion: kyma.kyma-project.io/v1alpha1
kind: LongOperation
metadata:
  name: longoperation-sample
spec:
  constantProcessingTime: 10
  randomProcessingTime: 5
  bigPayload: "veryLongPayloadHere maybe 10 KiB"
